services:
  node-a:
    build: ./p2p-node-service
    container_name: node-a
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - NODE_ID=node-a
      - NODE_FRAGMENTS_PATH=/data/fragments
      - NODE_OUTPUT_PATH=/data/output
      - NODE_PEERS_NODE_B=http://node-b:8080
      - NODE_PEERS_NODE_C=http://node-c:8080
    volumes:
      - ./data/node-a/fragments:/data/fragments
      - ./data/node-a/output:/data/output
    networks:
      - p2p-network

  node-b:
    build: ./p2p-node-service
    container_name: node-b
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - NODE_ID=node-b
      - NODE_FRAGMENTS_PATH=/data/fragments
      - NODE_OUTPUT_PATH=/data/output
      - NODE_PEERS_NODE_A=http://node-a:8080
      - NODE_PEERS_NODE_C=http://node-c:8080
    volumes:
      - ./data/node-b/fragments:/data/fragments
      - ./data/node-b/output:/data/output
    networks:
      - p2p-network

  node-c:
    build: ./p2p-node-service
    container_name: node-c
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - NODE_ID=node-c
      - NODE_FRAGMENTS_PATH=/data/fragments
      - NODE_OUTPUT_PATH=/data/output
      - NODE_PEERS_NODE_A=http://node-a:8080
      - NODE_PEERS_NODE_B=http://node-b:8080
    volumes:
      - ./data/node-c/fragments:/data/fragments
      - ./data/node-c/output:/data/output
    networks:
      - p2p-network

networks:
  p2p-network: