spring.application.name=p2p-node-service
server.port=8080

node.id=node-a
node.fragments-path=../data/node-a/fragments
node.output-path=../data/node-a/output

springdoc.swagger-ui.path=/swagger-ui.html