spring.application.name=p2p-node-service
server.port=8080

node.id=node-a
node.fragments-path=../data/node-a/fragments
node.output-path=../data/node-a/output

node.peers.node-b=http://localhost:8081
node.peers.node-c=http://localhost:8082

springdoc.swagger-ui.path=/swagger-ui.html